### PR TITLE
IBM cloud integration

### PR DESCRIPTION
**Pull request by amit4j**

### CODE REVIEW

**Comment by xuanxuan12** [comment]
In config.py, you commented out few lines, Do we need these lines to enable the connection to elephantsql?

**Comment by xuanxuan12** [comment]
In manifest,yml, should we add   
services:
  - ElephantSQL

**Review by xuanxuan12 — COMMENTED** [review]
In config.py, you commented out few lines, Do we need these lines to enable the connection to elephantsql?

In manifest,yml, should we add
services:
- ElephantSQL

**Comment by amit4j** [comment]
@xuanxuan12 I've changed it to just rely on the `DATABASE_URL` environment variable to get the connection string to the DB. 

As I see it, the service is hitting this [db](https://api.elephantsql.com/console/72f5c41a-0ce9-4b7d-b107-8d42403fa103/browser?#), and working as expected

**Review by xuanxuan12 — APPROVED** [review]

**Pull request merged**
